name: Code Scanning

on:
  pull_request:
    branches:
      - master

jobs:
  scan-code:
    runs-on: ubuntu-latest
#scanstart
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: pip install bandit

    - name: Run Bandit
      run: bandit -r .

    - name: Check Bandit results and comment on PR
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { data: { items } } = await github.pulls.list({ owner: context.repo.owner, repo: context.repo.repo });
          const pr_number = items[0].number;
          const banditResults = require('fs').readFileSync('bandit_results.txt', 'utf8');
          if (banditResults.includes('No issues identified')) {
            github.issues.createComment({
              issue_number: pr_number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Successful'
            });
          } else {
            github.issues.createComment({
              issue_number: pr_number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Block'
            });
          }
